### ISSUE TITLE
Compiler errors, is Go 1.7.5 too old?

### ISSUE THREAD

**Issue by metaleap** [a-h/generate#20]
Or is the `cmd` sub-package not intended to be built?

    [17:49 me ~/.../github.com/metaleap]$ go get github.com/a-h/generate
    [17:58 me ~/.../github.com/metaleap]$ go get github.com/a-h/generate/jsonschema
    [18:01 me ~/.../github.com/metaleap]$ go get github.com/a-h/generate/cmd/schema-generate
    # github.com/a-h/generate/cmd/schema-generate
    ../a-h/generate/cmd/schema-generate/main.go:46: jsonError.Struct undefined (type *json.UnmarshalTypeError has no field or method Struct)
    ../a-h/generate/cmd/schema-generate/main.go:46: jsonError.Field undefined (type *json.UnmarshalTypeError has no field or method Field)

**Comment by a-h** [comment]
Oh, sorry, I added some nice error messages in response to https://github.com/a-h/generate/issues/10 and used features added in Go 1.8 to get the struct name and field name which caused the problem (https://github.com/golang/go/commit/b9fd510cd00b6aa26e2ea7001a07b90ebf97d2ed)

If you run it using Go 1.8, it will work fine, or feel free to hack out the offending bits of the main.go file. 😀

**Comment by metaleap** [comment]
Ah I see, no prob, might wanna put it in the readme  =)  I only update golang when Fedora's package manager does
