### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by baconalot** [a-h/generate#22]
Your code looks promising, and I would like to modify some parts of it. You however have no license attached to it. Is that intentional?

**Comment by a-h** [comment]
Thanks! Not attaching a license was unintentional - I just didn't think about it. I've added an MIT license today.

**Comment by a-h** [comment]
Pull requests graciously accepted, of course!

**Comment by baconalot** [comment]
Thanks, ill have some fixes upcoming...
